### ISSUE TITLE
BBCode Conversion loosing some tag

### ISSUE THREAD

**Issue by akhoury** [akhoury/bbcode-to-markdown#1]
opened by @andreapernici 
https://github.com/akhoury/nodebb-plugin-import/issues/73

**Comment by andreapernici** [comment]
Two examples:

partendo da [url]qui[/url].

[font]AB-CD ipsum, lorem, ipsum? Perchè ipsum (lorem, ipsum è ovvio che non lo è)! :D[/font]

**Comment by andreapernici** [comment]
Or bbcode inside list
1. *_conoscere l'argomento
   *_
2. [b]conoscere il pubblico[/b]
3. [b]conoscere le obiezioni e i problemi del pubblico[/b]
