### ISSUE TITLE
Whitespaces before bbcode closing tag cause improper rendering of markdown

### ISSUE THREAD

**Issue by ghost** [akhoury/bbcode-to-markdown#4]
Whitespaces just before a closing tag should be moved after that tag.
Minimal example

```
This should be [b]bold [/b], but it is rendered as **bold ** ,
But if space is extracted and moved: **bold** , it will be rendered properly.
```

**Comment by akhoury** [comment]
so we're suppose to strip out the edge whitespaces? can you of reason why would the whitespace be intentional? if not, I think i can manage to strip them out.

**Comment by ghost** [comment]
Whitespaces are needed to seperate words i.e. 

```
Dogs[b] are [/b]very funny.
```

We can't just strip it, because it render something like "Dogs**are**very funny" after conversion. In phpbb `[b]bold(space)[/b]` and `[b]bold[/b](space)` looks the same after rendering, so i think users wouldn't bother if space is in or outside of tag.

**Comment by akhoury** [comment]
ah - so the rule is, don't strip, move out of the bounding style

**Comment by akhoury** [comment]
fixed when i switched to using [to-markdown](https://github.com/domchristie/to-markdown)
